floran/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf.urls.static import static
urlpatterns = [
    path('admin7039691123/', admin.site.urls),
    path('',include('mainpage.urls')),
   
    path('student/',include('student.urls')),
    path('manage/',include('management.urls')),
    path('create_user/', include('create_users.urls')),
    path('staff/', include('staffs.urls')),
    path('element/', include('elements.urls')),
    path('attendace/', include('attendance.urls')),
    path('result/', include('result.urls')),
    
    path('profile/',user_views.profile, name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

staffs/urls.py
from django.urls import path

from .views import *

urlpatterns = [
  path('list/', StaffListView.as_view(), name='staff-list'),
  path('<int:pk>/', StaffDetailView.as_view(), name='staff-detail'),
  path('create/', StaffCreateView.as_view(), name='staff-create'),
  path('<int:pk>/update/', StaffUpdateView.as_view(), name='staff-update'),
  path('<int:pk>/delete/', StaffDeleteView.as_view(), name='staff-delete'),
  path('downloadcsv', downloadcsv, name='staff-download-csv'),
  path('export', bulkUpload, name='staff-export'),
  path('import', csv_to_staff_database, name='staff-import'),

  path('head/list/', HeadListView.as_view(), name='head-list'),
  path('head/<int:pk>/', HeadDetailView.as_view(), name='head-detail'),
  path('head/create/', HeadCreateView.as_view(), name='head-create'),
  path('head/<int:pk>/update/', HeadUpdateView.as_view(), name='head-update'),
  path('head/<int:pk>/delete/', HeadDeleteView.as_view(), name='head-delete'),
]

staffs/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.core.validators import RegexValidator
from management.models import *

class Staff(models.Model):
  STATUS = [
      ('assistant', 'Assistant'),
      ('lecturer', 'Lecturer')
  ]

  GENDER = [
      ('male', 'Male'),
      ('female', 'Female')
  ]

  current_status      = models.CharField(max_length=10, choices=STATUS, default='assistant')
  staff_id_number     = models.IntegerField() 

  surname             = models.CharField(max_length=200)
  firstname           = models.CharField(max_length=200)
  
  # Subject             = models.ForeignKey(Subject, on_delete=models.SET_NULL, blank=True, null=True)

  gender              = models.CharField(max_length=10, choices=GENDER, default='male')
  date_of_birth       = models.DateField(default=timezone.now)

  date_of_join   = models.DateField(default=timezone.now)

  mobile_num_regex    = RegexValidator(regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!")
  mobile_number       = models.CharField(validators=[mobile_num_regex], max_length=13, blank=True)
  
  address             = models.TextField(blank=True)
  

  def __str__(self):
    return f'{self.surname} {self.firstname}'

  def get_absolute_url(self):
    return reverse('staff-detail', kwargs={'pk': self.pk})


class Head(models.Model):
  STATUS = [
      ('head', 'Head'),
      ('dean', 'Dean'),
      ('director', 'Director'),
  ]

  GENDER = [
      ('male', 'Male'),
      ('female', 'Female')
  ]

  surname             = models.CharField(max_length=200)
  firstname           = models.CharField(max_length=200)

  # department          = models.ForeignKey(Department,on_delete=models.CASCADE)
  title               = models.CharField(max_length=10, choices=STATUS, default='head')

  gender              = models.CharField(max_length=10, choices=GENDER, default='male')

  fromDate            = models.DateField(default=timezone.now)
  toDate              = models.DateField(default=timezone.now)

  def __str__(self):
    return f'{self.surname} {self.firstname}'

  def get_absolute_url(self):
    return reverse('head-detail', kwargs={'pk': self.pk})

staffs/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import *
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.forms import widgets
from django.urls import reverse_lazy
from .models import Staff,Head
from .resources import *
from datetime import datetime
import csv
from tablib import Dataset
####################################
############ StaffPart #############
####################################

class StaffListView(ListView):
    model = Staff

class StaffDetailView(DetailView):
    model = Staff
    template_name = "staffs/staff_detail.html"

class StaffCreateView(SuccessMessageMixin, CreateView):
    model = Staff
    fields = '__all__'
    success_message = 'New staff successfully added'

    def get_form(self):
        '''add date picker in forms'''
        form = super(StaffCreateView, self).get_form()
        form.fields['date_of_birth'].widget = widgets.DateInput(
            attrs={'type': 'date'})
        form.fields['date_of_join'].widget = widgets.DateInput(attrs={
                                                                    'type': 'date'})
        form.fields['address'].widget = widgets.Textarea(attrs={'rows': 1})
        
        return form

class StaffUpdateView(SuccessMessageMixin, UpdateView):
    model = Staff
    fields = '__all__'
    success_message = "Record successfully updated."

    def get_form(self):
        '''add date picker in forms'''
        form = super(StaffUpdateView, self).get_form()
        form.fields['date_of_birth'].widget = widgets.DateInput(
            attrs={'type': 'date'})
        form.fields['date_of_join'].widget = widgets.DateInput(attrs={
                                                                    'type': 'date'})
        form.fields['address'].widget = widgets.Textarea(attrs={'rows': 1})
        
        return form

class StaffDeleteView(DeleteView):
  model = Staff
  success_url = reverse_lazy('staff-list')

@login_required
def bulkUpload(request):
    student_resources = staffResources()
    dataset = student_resources.export()

    # exporting file here
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="staff-data.csv"'
    return response  
    
@login_required
def downloadcsv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="staff_data_to_be_import.csv"'

    writer = csv.writer(response)
    writer.writerow(['current_status',
                    'staff_id_number',
                     'surname',
                     'firstname', 
                     'gender',
                     'date_of_birth',
                     'date_of_join',
                     'mobile_number',
                     'address',
                     ])

    return response
    
@login_required  
def csv_to_staff_database(request):
    if request.method == 'POST':
        staff_resource = staffResources()
        dataset = Dataset()
        new_employees = request.FILES['importstaffData']
        imported_data = dataset.load(new_employees.read().decode('utf-8'),format='csv')
        
        data = [
            Staff(
                current_status = i[0],
                staff_id_number = i[1],
                surname = i[2],
                firstname = i[3],
                gender = i[4],
                date_of_birth = datetime.strptime(i[5],'%m/%d/%Y').strftime('%Y-%m-%d'),
                date_of_join = datetime.strptime(i[6],'%m/%d/%Y').strftime('%Y-%m-%d'),
                mobile_number = i[7],
                address = i[8],
            ) for i in imported_data 
        ]

        print(len(data))

        Staff.objects.bulk_create(objs=data)
        return redirect('staff-list')

    return render(request, 'staffs/import_sims.html')  
    
####################################
##### Head of Department Part ######
####################################

class HeadListView(ListView):
    model = Head

class HeadDetailView(DetailView):
    model = Head
    template_name = "staffs/head_detail.html"

class HeadCreateView(SuccessMessageMixin, CreateView):
    model = Head
    fields = '__all__'
    success_message = 'New Head successfully added'

    def get_form(self):
        '''add date picker in forms'''
        form = super(HeadCreateView, self).get_form()
        form.fields['fromDate'].widget = widgets.DateInput(
            attrs={'type': 'date'})
        form.fields['toDate'].widget = widgets.DateInput(attrs={
                                                                    'type': 'date'})
        
        return form

class HeadUpdateView(SuccessMessageMixin, UpdateView):
    model = Head
    fields = '__all__'
    success_message = "Record successfully updated."

    def get_form(self):
        '''add date picker in forms'''
        form = super(HeadUpdateView, self).get_form()
        form.fields['fromDate'].widget = widgets.DateInput(
            attrs={'type': 'date'})
        form.fields['toDate'].widget = widgets.DateInput(attrs={
                                                                    'type': 'date'})
        
        return form

class HeadDeleteView(DeleteView):
  model = Head
  success_url = reverse_lazy('head-list')

staffs/templates/staffs/head_confirm_delete.html
{% extends 'home.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this head will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

staffs/templates/staffs/head_detail.html
{% extends 'home.html' %}


{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool">Print</a>
    <a href="{% url 'head-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'head-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
    <div class="row">
      <div class="col-sm-4">
        <div>
          <h2>{{ object.get_title_display }} </h2>
          <br>
          <h3>{{ object }} </h3>
          <h5>{{ object.get_gender_display }} </h5>
          
        </div>
      </div>
      <div class="col-sm-8">
        <div>
          <div class="form-group border-bottom row">
            <label class="col">
              Department
            </label>
            <div class="col">
              {{ object.department }}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
               From 
            </label>
            <div class="col">
              {{ object.fromDate}}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              To
            </label>
            <div class="col">
              {{ object.toDate }}
            </div>
          </div>
          

        </div>

      </div>
    </div>




{% endblock content %}

staffs/templates/staffs/head_form.html
{% extends 'home.html' %}


{% block title %}

  {% if object %}
    Update {{ object }}
  {% else %}
    Add new Head
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  {% include 'form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new Head">
  {% endif %}
</form>


{% endblock content %}

staffs/templates/staffs/head_list.html
{% extends 'home.html' %}

{% block title %}Head{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'head-create' %}"><i
    class="fas fa-plus"></i> New Head</a>
{% endblock breadcrumb %}

{% block content %}
<div class="table-responsive">
  <table id="headtable" class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>S/N</th>
        <th>Fullname</th>
        <th>Gender</th>
        <th>Mobile Phone Number</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>

      {% for head in object_list %}
        <tr class='clickable-row' data-href="{% url 'head-detail' head.id %}">
          <td>{{ forloop.counter}}</td>
          <td>{{ head.surname}} {{head.firstname }}</td>
          <td>{{ head.get_gender_display}}</td>

          <td>{{ head.mobile_number}}</td>
          
          <td>{{ head.get_current_status_display}}</td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
</div>
{% endblock content %}


{% block morejs %}
<script>
   $('#headtable').DataTable({
    select: false
    });
</script>

{% endblock morejs %}

staffs/templates/staffs/import_sims.html
{% extends 'home.html' %}

{% block title %}
  Upload Bulk Staff from file
{% endblock title %}


{% block content %}

  <div class="col alert alert-info">
    <h4>Instruction</h4>
    <p>Please <a href="{% url 'staff-download-csv' %}">download the CSV file attached here</a>. Fill in the sheet and upload the same file back to this page. DO NOT EDIT THE FIRST ROW</p>
  </div>
    <p>
        <h3>Points to be noted</h3>
        <ul>
            <li>Enter the date of birth and date of join in the format of MM/DD/YYYY</li>
    </p>
    <h3>Import Data</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="importstaffData">
    <button class="btn btn-primary" type="submit">Import</button>
  </form>


{% endblock content %}

staffs/templates/staffs/staff_confirm_delete.html
{% extends 'home.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this Teacher will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

staffs/templates/staffs/staff_detail.html
{% extends 'home.html' %}


{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool">Print</a>
    <a href="{% url 'staff-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'staff-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
    <div class="row">
      <div class="col-sm-4">
        <div>
          <h3>{{ object }} </h3>
          <h6>{{ object.get_gender_display }} </h6>
          <h6>{{ object.get_current_status_display }} </h6>
        </div>
      </div>
      <div class="col-sm-8">
        <div>
          <div class="form-group border-bottom row">
            <label class="col">
              Sr no
            </label>
            <div class="col">
              {{ object.staff_id_number }}
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Date of Birth
            </label>
            <div class="col">
              {{ object.date_of_birth }}
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Date of join
            </label>
            <div class="col">
              {{ object.date_of_join }}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
               Mobile Number
            </label>
            <div class="col">
              {{ object.mobile_number}}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Address
            </label>
            <div class="col">
              {{ object.address }}
            </div>
          </div>
          

        </div>

      </div>
    </div>




{% endblock content %}

staffs/templates/staffs/staff_form.html
{% extends 'home.html' %}


{% block title %}

  {% if object %}
    Update {{ object }}
  {% else %}
    Add new Teacher
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  {% include 'form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new Teacher">
  {% endif %}
</form>


{% endblock content %}

staffs/templates/staffs/staff_list.html
{% extends 'home.html' %}

{% block title %}Teacher{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'staff-create' %}"><i
    class="fas fa-plus"></i> New Teacher</a>
<a class="btn btn-primary" href="{% url 'staff-import' %}"><i class="fas fa-user-plus"></i> Upload Bulk Staff data</a>

{% endblock breadcrumb %}

{% block content %}
<div class="table-responsive">
<a class="btn btn-primary" href="{% url 'staff-export' %}">Download the csv file of staff data </a>
<br><br>
  <table id="stafftable" class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>S/N</th>
        <th>Fullname</th>
        <th>Gender</th>
        <th>Mobile Phone Number</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>

      {% for staff in object_list %}
        <tr class='clickable-row' data-href="{% url 'staff-detail' staff.id %}">
          <td>{{ forloop.counter}}</td>
          <td>{{ staff.surname}} {{staff.firstname }}</td>
          <td>{{ staff.get_gender_display}}</td>

          <td>{{ staff.mobile_number}}</td>
          
          <td>{{ staff.get_current_status_display}}</td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
</div>
{% endblock content %}


{% block morejs %}
<script>
   $('#stafftable').DataTable({
    select: false
    });
</script>

{% endblock morejs %}